### ISSUE TITLE
Expected values for components and sections

### ISSUE THREAD

**Issue by nicojdejong** [ThomasKur/M365Documentation#36]
I had a look around for a list of valid component and section names, but could not find them easily. Any guidance?

**Comment by itsTerryDuckett** [comment]
I'm having the same issue. Where did you happen to find the component and section names?

**Comment by Snovex** [comment]
Had to review the code in order to understand what it was doing. But it sums up to this:

In order to see what subsections you get from your code, you need to first run:

`$doc = Get-M365Doc -Components Intune`

After that, you can use the following to see what subsections you get:

`$doc.SubSections`

You'll notice that you'll receive an error when typing in some of the titles from the subsections when you want to include or exclude certain sections. The real titles of all the subsections, you'll find here:

https://github.com/ThomasKur/M365Documentation/tree/main/PSModule/M365Documentation/Internal/Collector/Intune

That means the variables you must use to exclude subsections (if you're not interested in having everything in your report for example) is as follows:

MdmAdmxConfigurationProfile
MdmAppleConfiguration
MdmAutopilotProfile
MdmCompliancePolicy
MdmConfigurationPolicy
MdmConfigurationProfile
MdmDeviceCategory
MdmEnrollmentConfiguration
MdmExchangeConnector
MdmPartner
MdmPowerShellScript
MdmSecurityBaseline
MdmTermsAndCondition
MdmWindowsUpdate
MobileApp
MobileAppConfiguration
MobileAppDetailed
MobileAppManagement

Hope it helps others!

**Comment by stephanvandekruis** [comment]
Yes also looking for this. I tried -Components Azure -ExcludeSections "Domains" but domains is not vallid

**Comment by chris-alben** [comment]
Appreciate this is a little old, but for those interested in the future.

-Component Values: AzureAD, CloudPrint, InformationProtection, Intune, Windows365
Where you wish to document multiple workloads, separate each component with a comma, so for example, if needing to document Intune, Azure AD and Information Protection, the command would look as follows:

`Get-M365Doc -Components AzureAD,Intune,InformationProtection`

Sections are as follows:
AzureAD: `AADAdministrativeUnit`. `AADAuthMethod`,` AADBranding`, `AADConditionalAccess`, `AADConditionalAccessSplit`, `AADDirectoryRole`, `AADDomain`, `AADIdentityProvider`, `AADOrganization`, `AADPolicy`, `AADSubscription`

CloudPrint: `CPConnector`, `CPPrinter`

InformationProtection: `MIPLabel`

Intune: `MdmAdmxConfigurationProfile`, `MdmAppleConfiguration`, `MdmAutopilotProfile`, `MdmCompliancePolicy`, `MdmConfigurationPolicy`, `MdmConfigurationProfile`, `MdmDeviceCategory`, `MdmEnrollmentConfiguration`, `MdmExchangeConnector`, `MdmPartner`, `MdmPowerShellScript`, `MdmSecurityBaseline`, `MdmTermsAndCondition`, `MdmWindowsUpdate`, `MobileApp`, `MobileAppConfiguration`, `MobileAppDetails`, `MobileAppManagement`

Windows365: `W365Image`, `W365OnPremConnection`, `W365ProvisionProfile`, `W365UserSettings`

**Comment by ThomasKur** [comment]
Is the AutoComplete not working? like described in issue #42? When I test, I can leverage tab to get all the possible values... but if this does not work there is somewhere also a bug?

**Comment by ThomasKur** [comment]
No answer and not able to reproduce.
